[linux-vuplus_4.1.20] Add missing patches
Fix compile error:
/root/openvision-development-platform/build/tmp/work-shared/vuzero4k/kernel-source/include/linux/compiler-gcc.h:121:1: fatal error: linux/compiler-gcc9.h: No such file or directory
|   121 | #include gcc_header(__GNUC__)
|       | ^~~~
| compilation terminated.
| /root/openvision-development-platform/build/tmp/work-shared/vuzero4k/kernel-source/scripts/Makefile.build:153: recipe for target 'scripts/mod/devicetable-offsets.s' failed
| make[4]: *** [scripts/mod/devicetable-offsets.s] Error 1
| make[4]: *** Waiting for unfinished jobs....
|   SHIPPED scripts/dtc/dtc-parser.tab.c
|   HOSTCC  scripts/dtc/dtc-lexer.lex.o
|   HOSTCC  scripts/dtc/dtc-parser.tab.o
| /root/openvision-development-platform/build/tmp/work-shared/vuzero4k/kernel-source/scripts/Makefile.build:403: recipe for target 'scripts/mod' failed
| make[3]: *** [scripts/mod] Error 2
| make[3]: *** Waiting for unfinished jobs....
|   HOSTLD  scripts/dtc/dtc